export { SecundaryInput } from "./secundaryInput";
export { ReturnButton } from "./returnButton";
export { PrimaryInput } from "./primaryInput";
export { PrimaryButton } from "./primaryButton";
export { SecundaryButton } from "./SecundaryButton";
export { SkillsBalls } from "./SkillsBalls";
export { PorcentageBall } from "./PorcentageBall";
export { Logo } from "./Logo";
export { LoadingVideos } from "./LoadingVideos";